### ISSUE TITLE
meson build tool

### ISSUE THREAD

**Issue by bioinfornatics** [symmetryinvestments/jupyter-wire#16]
First thanks for your works

I would like to know if it is  possible to support meson as build tool ?

thanks

best regard

**Comment by Laeeth** [comment]
Sure.  A pull request would be very welcome.  However we are a small company and don't currently use Meson for pure D projects and it wouldn't be possible for us to do this ourselves any time soon.

**Comment by atilaneves** [comment]
Feel free to open a PR for meson support.
