### ISSUE TITLE
Should work on windows

### ISSUE THREAD

**Issue by John-Colvin** [symmetryinvestments/jupyter-wire#2]
As far as I can tell, the example nor the SIL backend work on windows.

**Comment by John-Colvin** [comment]
After juggling library dependencies, I get this:
```
> dub --arch=x86_mscoff -- kernel.json
< blah blah blah>
Running .\example_kernel.exe kernel.json
2019-01-14T21:09:21.293:..\source\jupyter\wire\kernel.d:main:14 Error: No error
Program exited with code 1
```

The `Error: No error` traces back to zmq_bind failing

**Comment by atilaneves** [comment]
How urgent is this?

**Comment by John-Colvin** [comment]
I'd really like it to be ready in the next few weeks if possible. I'm so fed up of Excel, the more people who can use jupyter notebooks as a front-end the better.

Do you know how much work it's likely to be?

**Comment by atilaneves** [comment]
Probably not a lot of work. It hasn't been done because it wasn't urgent and lot of other things were.

**Comment by atilaneves** [comment]
Probably not a lot of work. It hasn't been done because it wasn't urgent and lot of other things were.
