### ISSUE TITLE
d interpreter with jupyter-wire

### ISSUE THREAD

**Issue by joequant** [symmetryinvestments/jupyter-wire#28]
How difficult would it be to put in a dlang repl loop with a jupyter-wire.  Something like xeus-cling.

**Comment by joequant** [comment]
It looks like adding connecting jupyter-wire with drepl should do the trick.

**Comment by skoppe** [comment]
I haven't looked at drepl, but if its any good, it should be straightforward.

**Comment by joequant** [comment]
Trying to integrate drepl with jupyter-wire on branch dlang_kernel on branch joequant

I've got the kernel talking to the drepl.  Still getting errors, but would appreciate some feedback if I'm doing something wrong.

**Comment by joequant** [comment]
The error I'm getting is...

Error: Cannot open file `/tmp/drepl.DUM7Rh/_mod0.d' in mode `w' (No such file or directory)

What I think is happening is that when the interpreter goes out of scope, it removes the temporary directories.  What I want to do is to create one interpreter for each kernel.  The trouble that I run into is that when I create the drepl statically, there are system calls that can't be created statically.

**Comment by atilaneves** [comment]
It's not in the remit of jupyter-wire to implement any kernel, but to allow kernels to be written easily.
